name: Build'n'Release

on:
  push:
    branches: [ master ]

jobs:
  Style:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - run: git submodule update --init
      - name: Setup Python 3.10
        uses: actions/setup-python@v2
        with:
          python-version: "3.10"
      - name: Install Python dependencies
        run: pip install -e .[test]
      - run: make style
  Tests:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-20.04, macos-10.15 ]
        python-version: [ "3.7", "3.8", "3.9", "3.10" ]
    steps:
      - uses: actions/checkout@v2
      - run: git submodule update --init
      - name: Setup Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install Python dependencies
        run: pip install -e .[test]
      - name: Functional Tests
        run: make test-functional
      - name: Unit Tests
        run: make test-unit
  SonarCloud:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - run: git submodule update --init
      - name: Unshallow
        run: git fetch --unshallow
      - name: SonarCloud Scan
        uses: sonarsource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
  PublishSdist:
    name: Build and publish sdist
    runs-on: ubuntu-20.04
    needs:
      - Tests
      - Style
      - SonarCloud
    steps:
      - uses: actions/checkout@v2
      - run: git submodule update --init
      - uses: actions/setup-python@v2
        with:
          python-version: "3.9"
      - run: python setup.py sdist
      - run: pip install twine==3.4.*
      - name: Publish package to pypi
        env:
          TWINE_USERNAME: ${{ secrets.TWINE_USERNAME }}
          TWINE_PASSWORD: ${{ secrets.TWINE_PASSWORD }}
        run: twine upload dist/*
      - name: Set PKG_VERSION environment variable
        run: echo "PKG_VERSION=$(make -s get-version)" >> $GITHUB_ENV
      - name: Create GitHub release
        uses: softprops/action-gh-release@v1
        with:
          name: ${{ env.PKG_VERSION }}
          tag_name: ${{ env.PKG_VERSION }}
          body_path: changelogs/${{ env.PKG_VERSION }}.md
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  PublishWheels:
    name: Build and publish wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    needs:
      - Tests
      - Style
      - SonarCloud
      - PublishSdist
    strategy:
      matrix:
        os: [ ubuntu-20.04, macos-10.15 ]
    steps:
      - uses: actions/checkout@v2
      - run: git submodule update --init
      - name: Build wheels
        uses: pypa/cibuildwheel@v2.1.2
        env:
          CIBW_ARCHS: native
      - uses: actions/setup-python@v2
        with:
          python-version: "3.9"
      - run: pip install twine==3.4.*
      - name: Publish wheels to pypi
        env:
          TWINE_USERNAME: ${{ secrets.TWINE_USERNAME }}
          TWINE_PASSWORD: ${{ secrets.TWINE_PASSWORD }}
        run: twine upload wheelhouse/*
